// <auto-generated />
namespace CinemaTiket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class themcotvaonamevaobangnetuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(themcotvaonamevaobangnetuser));
        
        string IMigrationMetadata.Id
        {
            get { return "202303131706234_them cot vao name vao bang netuser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
